/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p resourcewatcherconnectioninterface /home/joerg/Development/KDE/nepomuk-core/interfaces/org.kde.nepomuk.ResourceWatcherConnection.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef RESOURCEWATCHERCONNECTIONINTERFACE_H_1328435058
#define RESOURCEWATCHERCONNECTIONINTERFACE_H_1328435058

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.kde.nepomuk.ResourceWatcherConnection
 */
class OrgKdeNepomukResourceWatcherConnectionInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.nepomuk.ResourceWatcherConnection"; }

public:
    OrgKdeNepomukResourceWatcherConnectionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgKdeNepomukResourceWatcherConnectionInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> addProperty(const QString &property)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(property);
        return asyncCallWithArgumentList(QLatin1String("addProperty"), argumentList);
    }

    inline QDBusPendingReply<> addResource(const QString &resource)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(resource);
        return asyncCallWithArgumentList(QLatin1String("addResource"), argumentList);
    }

    inline QDBusPendingReply<> addType(const QString &type)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(type);
        return asyncCallWithArgumentList(QLatin1String("addType"), argumentList);
    }

    inline QDBusPendingReply<> close()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("close"), argumentList);
    }

    inline QDBusPendingReply<> removeProperty(const QString &property)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(property);
        return asyncCallWithArgumentList(QLatin1String("removeProperty"), argumentList);
    }

    inline QDBusPendingReply<> removeResource(const QString &resource)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(resource);
        return asyncCallWithArgumentList(QLatin1String("removeResource"), argumentList);
    }

    inline QDBusPendingReply<> removeType(const QString &type)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(type);
        return asyncCallWithArgumentList(QLatin1String("removeType"), argumentList);
    }

    inline QDBusPendingReply<> setProperties(const QStringList &properties)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(properties);
        return asyncCallWithArgumentList(QLatin1String("setProperties"), argumentList);
    }

    inline QDBusPendingReply<> setResources(const QStringList &resources)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(resources);
        return asyncCallWithArgumentList(QLatin1String("setResources"), argumentList);
    }

    inline QDBusPendingReply<> setTypes(const QStringList &types)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(types);
        return asyncCallWithArgumentList(QLatin1String("setTypes"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void propertyAdded(const QString &resource, const QString &property, const QVariantList &values);
    void propertyChanged(const QString &resource, const QString &property, const QVariantList &oldValues, const QVariantList &newValues);
    void propertyRemoved(const QString &resource, const QString &property, const QVariantList &values);
    void resourceCreated(const QString &uri, const QStringList &types);
    void resourceRemoved(const QString &uri, const QStringList &types);
    void resourceTypeAdded(const QString &resUri, const QString &type);
    void resourceTypeRemoved(const QString &resUri, const QString &type);
};

namespace org {
  namespace kde {
    namespace nepomuk {
      typedef ::OrgKdeNepomukResourceWatcherConnectionInterface ResourceWatcherConnection;
    }
  }
}
#endif
